name: firebase_auth_starter
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  freezed_annotation: ^2.0.3
  injectable: ^1.5.3
  json_annotation: ^4.5.0
  dartz: ^0.10.1
  kt_dart: ^0.10.0
  uuid: ^3.0.6
  flutter_bloc: ^8.0.1
  firebase_auth: ^3.3.18
  firebase_core: ^1.17.0
  google_sign_in: ^5.3.2
  cloud_firestore: ^3.1.16
  get_it: ^7.2.0
  auto_route: 4.0.0
  flutter_hooks: ^0.18.3
  file_picker: ^4.5.1
  firebase_storage: ^10.2.16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  injectable_generator: ^1.5.3
  auto_route_generator: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
